### ISSUE TITLE
Interpolating RegExps into charsets is dodgy

### ISSUE THREAD

**Issue by mikesamuel** [mikesamuel/regexp-make-js#2]
We don't properly check charset boundaries.

Perhaps we should make some effort to collapse ...|...|... and drop Kleene operators.

**Comment by erights** [comment]
I don't understand. Could you show an example?

**Comment by mikesamuel** [comment]
`[a]|[b]` would be treated as `[a\]|[b]`

**Comment by erights** [comment]
> [a]|[b] would be treated as [a]|[b]

Please explain. What's wrong with treating [a]|[b] as [a]|[b] ? I'm not getting it.

**Comment by mikesamuel** [comment]
Sorry.  WikiText strikes again.  Please see my edit.

**Comment by mikesamuel** [comment]
Fixed at https://github.com/mikesamuel/regexp-make-js/commit/4a48bddc264e41feff8b329ebf20392e2b2d8d86
