### ISSUE TITLE
When test fails to run in old browser, it should emit an explanation instead

### ISSUE THREAD

**Issue by erights** [mikesamuel/regexp-make-js#3]
Currently, on Chrome, Opera, and Safari, visiting https://rawgit.com/mikesamuel/regexp-make-js/master/test.html simply shows a blank page. You have to open the console to know what the problem is.

**Comment by erights** [comment]
Almost fixed by https://github.com/mikesamuel/regexp-make-js/commit/f4db12220eb5ef4d430d3536636888b9f8d387b9 but still fails on Chrome canary 46.0.2473.0. The reason seem to be that Chrome canary passes the ES6 test that the new test code tests for (... in a parameter list), but tests.js fails to parse due to missing a different feature of ES6 (const with a list destructuring pattern).

**Comment by mikesamuel** [comment]
Fixed at https://github.com/mikesamuel/regexp-make-js/commit/f4db12220eb5ef4d430d3536636888b9f8d387b9

**Comment by erights** [comment]
Did you try it on Canary? See my note. Reopening.
