### ISSUE TITLE
A capture-group-numbering test fails

### ISSUE THREAD

**Issue by erights** [mikesamuel/regexp-make-js#7]
See attached screenshots

![screen shot 2015-08-06 at 12 26 27 pm](https://cloud.githubusercontent.com/assets/273868/9121377/c22f4a88-3c36-11e5-8852-4323001612b9.png)
![screen shot 2015-08-06 at 12 24 43 pm](https://cloud.githubusercontent.com/assets/273868/9121378/c231914e-3c36-11e5-9222-a22dfdfa5313.png)

**Comment by mikesamuel** [comment]
That was a known failure.  It's fixed on my most recent branch.

**Comment by erights** [comment]
Works now.
